# ****** Localhost Requests ***********

### Get All Contacts
GET http://localhost:3000/contacts

### Get one Contact by id
GET http://localhost:3000/contacts/63bf8f2eff09293ad5ba3252


### Create New Contact
POST http://localhost:3000/contacts/ HTTP/1.1
Content-Type: application/json

{
    "firstName": "Jack",
    "lastName": "Black",
    "email": "jblack@test.com",
    "favoriteColor": "black",
    "birthday": "05-18-1975"
}


### Update Contact
PUT http://localhost:3000/contacts/63c0cf2fccceac6b2e0aeb9c HTTP/1.1
Content-Type: application/json

{
    "firstName": "Aaron",
    "lastName": "Jenkins"
}



### Delete Contact
DELETE http://localhost:3000/contacts/63ca29d501deea0a8cca697a



# ****** Render Requests ***********

### Get All Contacts
GET https://adamcse341.onrender.com/contacts

### Get one Contact by id
GET https://adamcse341.onrender.com/contacts/63bf8f2eff09293ad5ba3252


